#! /bin/sh

cp -a chroot-pdftk /usr/local
cp -a pdftk /usr/local/bin

gcc pdftk-wrap.c -o pdftk-wrap
strip pdftk-wrap
cp pdftk-wrap /usr/local/bin
setcap 'cap_sys_chroot+ep' /usr/local/bin/pdftk-wrap

mount -t proc /usr/local/chroot-pdftk/proc /usr/local/chroot-pdftk/proc
mkdir -p /usr/local/tmp; chmod 777 /usr/local/tmp; chmod +t /usr/local/tmp
mount --bind /usr/local/tmp/ /usr/local/chroot-pdftk/tmp/
